---
- name: Build docker image and push docker image
  hosts: docker-fe
  tasks:
    - name: Copy project files to docker host
      copy:
        src: "{{ item }}"
        dest: /home/ansadmin/frontend
      with_items:
        - Dockerfile
        - angular.json
        - package-lock.json
        - package.json 
        - src 
        - tsconfig.app.json
        - tsconfig.json
        - tsconfig.spec.json
    - name: Build docker image
      command: docker build -t sushila91/surajit:contact_ui_app /home/ansadmin/frontend  
    - name: Push docker image
      command: docker push sushila91/surajit:contact_ui_app
...       
